coverage:
  if: true
  exclude:
    - 'github.com/k1LoW/runn/tmpmod/**/*'
codeToTestRatio:
  code:
    - '**/*.go'
    - '!**/*_test.go'
    - '!testutil/*.go'
    - '!tmpmod/**/.go'
  test:
    - '**/*_test.go'
    - 'testutil/*.go'
    - '!tmpmod/**/.go'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
summary:
  if: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
